manifest:
  namespace: kubeflow
  name: kubeflow-platform
  repoURL: https://github.com/kubeflow/pipelines.git
  targetRevision: 2.16.1
  path: manifests/kustomize/env/cert-manager/platform-agnostic-k8s-native
